# Help found here:
# https://github.com/daattali/beautiful-jekyll/blob/master/_config.yml

# Set the theme for the website
theme: jekyll-theme-cayman

# Title
title: Rotate

# Subtitle
description: Rotate around the world

# Gets rid of "View on GitHub" button
is_project_page: false

# --- Navigation Bar --- #
# List of links in the navigation bar
navbar-links:
  Home: "README.md"
  Gallary:
    - Solo: ""
    - Group: ""
  Download: "https://apps.apple.com/us/app/rotate-3d-freeze-frame-pics/id1253508296"

# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
#avatar: "/img/avatar-icon.png"
